# Generated by Django 4.2.20 on 2025-03-10 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("softdeskApp", "0009_alter_project_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="age",
            field=models.PositiveIntegerField(),
        ),
    ]
