# Generated by Django 4.2.20 on 2025-03-10 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softdeskApp', '0010_alter_user_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(max_length=10),
        ),
    ]
