# Generated by Django 4.2.20 on 2025-03-10 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("softdeskApp", "0011_alter_project_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
