# Generated by Django 4.2.20 on 2025-03-11 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("softdeskApp", "0012_alter_project_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="type",
            field=models.CharField(
                choices=[
                    ("backend", "Back-end"),
                    ("frontend", "Front-end"),
                    ("ios", "iOS"),
                    ("android", "Android"),
                ],
                max_length=10,
            ),
        ),
    ]
